name: Playwright Tests CI/CD 🚀

on:
  push:
    branches:
      - "!main"
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up XVFB
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          # Kill any existing Xvfb process
          pkill Xvfb || true
          nohup Xvfb :99 -screen 0 1280x1024x24 &
          export DISPLAY=:99

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: xvfb-run npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
